package config

import (
	"gopkg.in/yaml.v2"
	"io/ioutil"
	"log"
)

type AutoGenerated struct {
	Mysql Mysql `yaml:"mysql"`
	QqBot QqBot `yaml:"qq_bot"`
}

type Mysql struct {
	Db       string `yaml:"db"`
	User     string `yaml:"user"`
	Password string `yaml:"password"`
	Host     string `yaml:"host"`
	Port     string `yaml:"port"`
}

type QqBot struct {
	Port string `yaml:"port"`
}

var Setting AutoGenerated

func InitConfig(filename string) {
	config, _ := ioutil.ReadFile(filename)
	err := yaml.Unmarshal(config, &Setting)
	if err != nil {
		log.Fatal("初始化配置失败")
	}
}
